services:
    synth_notification.notification_manager.default:
        class: %synth_notification.notification_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %synth_notification.notification.class%
